### ISSUE TITLE
Sur lister les étudiants, remplacer les "Choisir" pour TOUT afin d'afficher tous les étudiants.

### ISSUE THREAD

**Issue by simHuard** [dinfcll/sachem#11]

**Comment by jwallet** [comment]
on avait regarder guillaume anto et alex, ca lavait plus de sens de garder Choisir comme disait Josee puisque la recherche filtre les choix a partir de session, les autres dropdown sont donc des choix obligatoire, si on laisse sur choisir rien doit se passer donc cest pas un tous, les 3 dropdownlist doivent etre selectionnes pour que la recherche fonctionne.

**Comment by jwallet** [comment]
done

**Comment by olafleur** [comment]
Idéalement, ne pas closer l'issue tant que la PR n'est pas mergée.

**Comment by olafleur** [comment]
C'est mieux de mettre dans la colonne Ready dans le Projet.
