### ISSUE TITLE
[feature] ajout de page commentaires / forums

### ISSUE THREAD

**Issue by jwallet** [dinfcll/sachem#111]

**Comment by jwallet** [comment]
Forum chu vraiment pas pour . Jsais pas pour vous... Cetait pas pire en 2000 mais de nos jours live chat cest pas mal la reponse. Donc jpropose oui a la page commentaire ca peut etre un pas pire addon mais peut etre plus dajouter un lien rocket chat a un canal que de programmer un forum autant inutile que ceux sur omnivox. Oui omnivox en a pour chaque classe et en 4 ans de cegep seulement un prof la utiliser mais ses eleves... non! Jpense plus faire un systeme de messagerie interne qui viendrait se placer a gauche de licone de connexion dans nav bar pour la lecture des messages et le lien pour envoyer serait sous celui de lemail dans chaque details de profil

**Comment by olafleur** [comment]
J'aime bien l'idée du lien vers Rocket.Chat, genre vers le channel #aide-informatique ;)

**Comment by jwallet** [comment]
Lien direct avec proposition de telecharger lapp windows et mobile pour rester connecter sinon ils peuvent toujours faire comme ceux avant eux et inscrire leur num de cellulaire

**Comment by jwallet** [comment]
Facebook cest pas mal apparemment
