### ISSUE TITLE
[messages] Centraliser les Messages succes/erreur/infos/questions dans le Model.Messages et retirer ceux "hard coder"

### ISSUE THREAD

**Issue by jwallet** [dinfcll/sachem#121]
Meme si y'en a beaucoup dans Model.Messages, il reste beaucoup de messages ecrit a main dans les controlleurs et vues au lieu des avoir mis en ordre dans la liste Model.Messages:
U_###, Q_###, I_###
ce sera plus facile d'acces pour la modification, le jour ou le safran ou sai sera implanter

**Comment by LeclercA** [comment]
je sais pas si tu las commencer ou non, mais en premier il faudrait faire un tri de tous les messages pour savoir lesquels se répétent et les quels sont semblables. Je peux le faire si ça te va.

**Comment by olafleur** [comment]
Pis en fait, je recommanderais qu'on enlève la structure des numéros de message pour remplacer par des noms significatifs. Les numéros de messages c'est pas cool quand y'a des conflits à gérer avec des messages différents pour le même numéro.

**Comment by jwallet** [comment]
Vas y cest good
