### ISSUE TITLE
[general] variables membres et constant privee en commun doivent aller dans le web.config

### ISSUE THREAD

**Issue by jwallet** [dinfcll/sachem#122]
voir les controlleurs s'il n'y a pas des constantes qui pourraient etre creees entre plusieurs controlleurs et le mettre dans le web.config pour modification future plus simple et rapide.
comme il a (ou sera fait) pour jumelage controlleur et inscription controlleur avec les constantes int DUREE_RENCONTRE_MINUTES, DEMI_HEURE, HEURE_DEBUT, HEURE_FIN...

**Comment by LeclercA** [comment]
Pour ceux qui veulent le faire, voici comment, super simple (hihihihi) : http://stackoverflow.com/questions/22249672/creating-custom-variable-in-web-config-file

**Comment by LeclercA** [comment]
cest mieux de les mettre dans le web.config que de leur faire une class @olafleur

**Comment by olafleur** [comment]
Oui, possiblement. :)
