### ISSUE TITLE
[controlleurs] centraliser les methodes communes de controlleurs

### ISSUE THREAD

**Issue by jwallet** [dinfcll/sachem#130]

**Comment by LeclercA** [comment]
Un peu la même chose qu'avec les listes ? Si oui, je peux le commencer.

**Comment by jwallet** [comment]
Oui mais j'ai remarquer que le monde avait créé un dossier classes sachem. Ca devrait aller dans un dossier qui porte pas ce nom vu qu'on se dirige vers un Core commun . Peut être les mettre dans modèle dossier yen a d'autres la déjà. Comme classe pour les case dans horaire inscription et disponibilité
