### ISSUE TITLE
[methodes] des methodes controlleurs et surtout AJAX non pas de validation d'Acces, verifier la securite

### ISSUE THREAD

**Issue by jwallet** [dinfcll/sachem#132]
- verifier les tags [validations acces] des methodes controlleurs et verifier le tag [nonAction]
- verifier la securite des methodes ajax, on pourrait appeler dans la vue le controlleur pour plus de securiter voir issue #129 pour voir comment.
- controlleurs
- [ ] account
- [ ] consulter cours
- [ ] contrat engagement
- [ ] cours
- [ ] cours suivi
- [x] dossier etudiant
- [ ] enseignant
- [ ] etudiant
- [ ] groupes
- [ ] home
- [ ] importer
- [ ] inscription
- [ ] jumelage
- [ ] parametres
- [ ] programmes offerts
- [ ] recherche inscription
- vues 
- [ ] account
- [ ] consulter cours
- [ ] contrat engagement
- [ ] cours
- [ ] cours suivi
- [ ] dossier etudiant
- [ ] enseignant
- [ ] etudiant
- [ ] groupes
- [ ] home
- [ ] importer
- [ ] inscription
- [ ] jumelage
- [ ] parametres
- [ ] programmes offerts
- [ ] recherche inscription

**Comment by LeclercA** [comment]
y'a aussi certain controller qui n'ont pas `[ValidationAcces]` comme sécurité
