### ISSUE TITLE
[francais] correction des vues et des messages

### ISSUE THREAD

**Issue by jwallet** [dinfcll/sachem#134]
passer les textes sur antidote ou utiliser votre savoir
- [x] classer les textes dans le fichier message.cs par controlleurs
- [ ] retirer les messages des controlleurs et les recrees dans le fichier message
- [ ] retirer les messages des vues dans le fichier message
- [ ] faire la correction des textes

**Comment by LeclercA** [comment]
Je ne suis pas un pirate ;)
