### ISSUE TITLE
[readme] maj de la documentation necessaire avant fin de session

### ISSUE THREAD

**Issue by jwallet** [dinfcll/sachem#135]
- [ ] Recuperation des infos manquantes avec les autres eleves
- [ ]  Infos sur le serveur
- [ ] ajouter qu'il faut passer par le `tableau des taches` pour prendre un issue selon la priorite et ajouter des issues (cards)
- [ ] informer que chaque fois que `master` est updater, le serveur le sera.
- [ ] que pour chaque pull request il faut informer quel issue ca va fermer avec # le numero issue.
- [ ] bien s'assigner les issues quand on commence a travailler dessus
- [ ] bien fermer les issues quand ils ont été merge
- [ ] informer que toutes les strings du site se trouvent dans messages.cs
- [ ]  indiquer quoi utiliser pour faire un test unitaire et comment mocker un controlleur en httpContext
- [ ] indiquer que chaque message afficher ou mots afficher doit passer par messages.cs que se soient des messages deja present ou nouveaux
- [ ]  indiquer que lon doit utiliser le idatarepository pour appeler la bd et on doit linitialiser deux fois un avec parametre pour test et un sans.
- [ ]  indiquer quil faut uitliser les methodes de la  classe datarepo pour faire ses appels a bd .. pas de requetes standard ou de linq du style from d where x . . Ou db.cours.where( x... mais datatepo.whereCours( x..
- [ ]  indiquer quels sont les méthodes de la classe datarepo pour appeler la bd. WhereTable FindTable AnyTable AllTable AddTable AddRangeTable EditTable RemoveTable RemoveRangeTable avec comme demo leurs parametres ()
- [ ] Expliquer comment utiliser les labels lors de la creation issues
- [ ] Indiquer qu'il faut attribuer les tags de tons Bleu lors du cheminement dans le TaskBoard (En developpement, Pull Request) et le retirer si le issue est ferme (mettre tag Ferme, si issue est non merger)
- [ ] indiquer qu'il faut utiliser material icones de Google pour inserer de nouvelles icones et prendre les liens `<i class="material icons">nom_icone</i>` pour les ajouter comme le site l'indique.  lien pour les icones : https://material.io/icons/, lien pour la doc : https://google.github.io/material-design-icons/
- (inscrivez vos points a la suite des miens)
-
-

**Comment by LeclercA** [comment]
- bien s'assigner les issues quand on commence a travailler dessus
- bien fermer les issues quand ils ont été merge

**Comment by jwallet** [comment]
- informer que toutes les strings du site se trouvent dans messages.cs
- indiquer quoi utiliser pour faire un test unitaire et comment mocker un controlleur en httpContext

**Comment by jwallet** [comment]
- indiquer que chaque message afficher ou mots afficher doit passer par messages.cs que se soient des messages deja present ou nouveaux
- indiquer que lon doit utiliser le idatarepository pour appeler la bd et on doit linitialiser deux fois un avec parametre pour test et un sans.
- indiquer quil faut uitliser les methodes de la  classe datarepo pour faire ses appels a bd .. pas de requetes standard ou de linq du style from d where x . . Ou db.cours.where( x... mais datatepo.whereCours( x..
- indiquer quels sont les méthodes de la classe datarepo pour appeler la bd. WhereTable FindTable AnyTable AllTable AddTable AddRangeTable EditTable RemoveTable RemoveRangeTable avec comme demo leurs parametres ()
