### ISSUE TITLE
Gérer inscription

### ISSUE THREAD

**Issue by simHuard** [dinfcll/sachem#14]
[Dossier fonctionnel](https://www.dropbox.com/s/0ja7qfnkwtz5acn/P490_G%C3%A9rer%20inscription.pdf?dl=0)
![gerer_inscription_-_recherche](https://cloud.githubusercontent.com/assets/23443246/20441801/ffdd44be-ad93-11e6-8897-e56ba080102f.PNG)
![gerer_inscription_-_detail](https://cloud.githubusercontent.com/assets/23443246/20441799/fecfe022-ad93-11e6-9f05-87532d35e02a.PNG)

**Comment by LeclercA** [comment]
Ce quil reste a faire :
- faire un tri dans l'index pour enlever les inscriptions brouillons
- dans details, envoyer une liste dinscription selon la personne 
- faire toute la logique de detail
