### ISSUE TITLE
voir pourquoi la police ne load pas correctement parfois

### ISSUE THREAD

**Issue by jwallet** [dinfcll/sachem#146]
![image](https://cloud.githubusercontent.com/assets/23088305/21120233/4c91aa4e-c094-11e6-8d4a-cd4ca72310ba.png)

**Comment by olafleur** [comment]
La console web va sûrement te donner un indice

**Comment by jwallet** [comment]
oh boy ! chrome cache :)

**Comment by olafleur** [comment]
Ha! Ha! :)
