### ISSUE TITLE
[INSCRIPTION - ValidationAccess] la validation d'afficher la page inscription apres la creation du compte plante

### ISSUE THREAD

**Issue by jwallet** [dinfcll/sachem#147]
![image](https://cloud.githubusercontent.com/assets/23088305/21120535/d2240098-c095-11e6-8606-ede9381aab47.png)

**Comment by olafleur** [comment]
Comme à la démo?

**Comment by jwallet** [comment]
Mon fix que javais fait ya quelques jours a disparu, jvais aller voir les commits

**Comment by jwallet** [comment]
oh ben, y'existe meme pu, chu pas contributeur de validationacess.cs

**Comment by olafleur** [comment]
Ah, y'a sûrement eu un mauvais merge à un moment donné. :(
