### ISSUE TITLE
Recherche étudiant

### ISSUE THREAD

**Issue by simHuard** [dinfcll/sachem#15]
![recherche_eleve](https://cloud.githubusercontent.com/assets/23443246/20442079/30b354ec-ad95-11e6-8bfa-37d6e1c72425.PNG)

**Comment by GuillaumePrudhomme** [comment]
Je pense qu'on l'a dit hier...mais je m'en souvient déja pu. C'est pour quoi ou quel controller / view qui faudrait ajouter ceci?

**Comment by VenablesA** [comment]
Je crois que c'est dans l'inscription, mais je ne suis pas certain.

**Comment by VenablesA** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/23405812/20627677/8c4d5280-b2ef-11e6-9706-91a905de6c12.png)

J'ai finalement trouver la même recherche dans le suivi des rencontres

**Comment by olafleur** [comment]
Si c'est quelque chose qui est dans plusieurs écrans, vous pouvez le faire une fois et le réutiliser à plusieurs endroits.
