### ISSUE TITLE
[contrat engagement] possibilite 'system.invalidOperationException'

### ISSUE THREAD

**Issue by jwallet** [dinfcll/sachem#156]
faire en sorte de gerer l'exception dans la vue et de peut etre le meme en test en plus ou la re-ecrire:
![image](https://cloud.githubusercontent.com/assets/23088305/21193634/f34e294a-c1fa-11e6-8572-f0c980a32341.png)
parce que je suis pas sur de ce que Resharper propose, on devrait le ramener a la vue et prendre un viewbag.
![image](https://cloud.githubusercontent.com/assets/23088305/21193684/15d2dad8-c1fb-11e6-91ed-c2c2f114a117.png)

**Comment by LeclercA** [comment]
Le probleme c'est que ContratEngagement est un type nullable, La vue aime pas ça... je vais regarder ça.

**Comment by LeclercA** [comment]
Voici une solution : `@if (Model.ContratEngagement != null && !(bool)Model.ContratEngagement)` comme ça on est sur qu'il est pas null donc pas d'erreur. Pas le choix de cast en bool car il est de type bool mais nullable
