### ISSUE TITLE
[vues] plusieurs vues (dont les recents features) ne suivent pas le meme pattern que les anciens

### ISSUE THREAD

**Issue by jwallet** [dinfcll/sachem#166]
cest tres optionnel, mais ca serait bien de garder le meme schema de vues avec les meme classes bootstrap utilisees, et d'utiliser les tags @Html... pour afficher le model que la vue n'utilise (d'ailleurs) pas comme dans Jumelage et Inscription... biensur si ca convient a la vue.

![refaire les vues inscription plus standard](https://cloud.githubusercontent.com/assets/23088305/21375757/e4bda646-c6fd-11e6-8a62-41ea2845b622.PNG)

**Comment by olafleur** [comment]
Oui, tu as raison, la consistance, c'est important.
