### ISSUE TITLE
MAJ Jumelage

### ISSUE THREAD

**Issue by simHuard** [dinfcll/sachem#18]
![maj_jumelage_-_chargement_en_cours](https://cloud.githubusercontent.com/assets/23443246/20442460/98d93798-ad96-11e6-96fa-0664d6affdb2.PNG)
![maj_jumelage_-_detail_-_jumelage_possible](https://cloud.githubusercontent.com/assets/23443246/20442473/a4253a8e-ad96-11e6-9e72-b50f282c1a30.PNG)
![maj_jumelage_-_detail_-_jumele_a](https://cloud.githubusercontent.com/assets/23443246/20442474/a5b24338-ad96-11e6-8256-d62d3634a6b8.PNG)
![maj_jumelage_-_recherche](https://cloud.githubusercontent.com/assets/23443246/20442476/a6c8aaf0-ad96-11e6-8838-f0c1539331cf.PNG)

**Comment by jwallet** [comment]
dans les cases vertes, les chiffres cest quoi exactement?

**Comment by olafleur** [comment]
Le nombre de tuteurs disponibles à cette plage horaire?

**Comment by jwallet** [comment]
![image](https://cloud.githubusercontent.com/assets/23088305/20540857/c2d25888-b0c8-11e6-84b8-9fe5ca7944eb.png)
