### ISSUE TITLE
depuis github > synchroniser la master provoque un erreur

### ISSUE THREAD

**Issue by jwallet** [dinfcll/sachem#34]
`Les erreurs suivantes ont été signalées lors du push :
	refs/heads/master, protected branch hook declined`

**Comment by jwallet** [comment]
surement a cause j'utilise l'application... jvais voir ca

**Comment by olafleur** [comment]
Si t'as pas de commits de plus que `master` , me semble que ça devrait pas faire de problème.
`git pull` ça te donne quoi?

**Comment by jwallet** [comment]
maintenant ca donne `already up-to-date` parce que jai pullé a partir de l'app github, je verrai la prochaine fois que je pull a partir de VS

**Comment by olafleur** [comment]
ok

**Comment by jwallet** [comment]
ma repo est en local parce que jutilise lapp. surement cest ca mon probleme

**Comment by jwallet** [comment]
jviens de retester avec la pr #31 et le sync sur VS marchait pas mais sur GitHub app marche. surement moi qui a mal configurer ma repo. en tout cas , cest fix
