### ISSUE TITLE
[consulter cours] dropdownlist de recherche doit conserver valeur au changement de page

### ISSUE THREAD

**Issue by jwallet** [dinfcll/sachem#64]
quand on utilise la recherche les dropdownlist ne contiennent pas les anciennes valeur au retour de page comme sous d'autres vues, voir dossier etudiants ou etudiants

![image](https://cloud.githubusercontent.com/assets/23088305/20822205/c31741f0-b816-11e6-823b-8ab314ee8d3e.png)

**Comment by olafleur** [comment]
On peut closer cette issue?
