### ISSUE TITLE
Fix validation d'accès inscription

### ISSUE THREAD

**Issue by DylanMarcotte** [dinfcll/sachem#69]

**Comment by olafleur** [comment]
Peux-tu mettre plus de détails sur le problème?

**Comment by DylanMarcotte** [comment]
La validation recevait une mauvaise date en param donc on ne pouvait jamais accéder à la page. Aussi, si on avait pas de groupe dans la BD, ca plantait. J'ai changé la méthode pour trouver la session actuelle!

**Comment by DylanMarcotte** [comment]
Fixed
