### ISSUE TITLE
Amélioration: Les checkbox de la page de disponibilités

### ISSUE THREAD

**Issue by DylanMarcotte** [dinfcll/sachem#72]
Sous Chrome, le CSS marche et le checkbox est plus gros et stylé (style de test, j'en ai essayé plusieurs donc on peut changer).

Sous Firefox, le checkbox est centré mais NON stylé. Il n'est pas plus gros non plus apparament.

Amélioration future: trouver un style pour firefox, ou faire un nouveau composant.

**Comment by olafleur** [comment]
Screenshot ?

**Comment by jwallet** [comment]
javais fait des recherches et ya rien qui se fait pour firefox pour les checkbox.
a part faire un scale et cest ugly as fuck.
la solution a plusieurs navigateur est de faire un hidden sur le checkbox et se faire un div label qui remplace le visuel du checkbox, tout ce fait en css mais pour juste faire ce petit changement , ca vaut pas la peine de creer x3 des balises pour ca.
autrement, firefox n'agrandit pas le checkbox visuellement, mais il agrandit la zone cliquable donc ca marche

`chrome`
![image](https://cloud.githubusercontent.com/assets/23088305/20840290/bc24fe0c-b87d-11e6-8ab7-1b5790f00259.png)

`firefox`
![image](https://cloud.githubusercontent.com/assets/23088305/20840320/d5b9134e-b87d-11e6-8516-b873d86357e6.png)
mais environ cette zone est cliquable
![image](https://cloud.githubusercontent.com/assets/23088305/20840351/f1bc4c82-b87d-11e6-957f-3ddeb3d31ca3.png)

**Comment by jwallet** [comment]
jarrive a de quoi jpense
jai mis un `<span>` a place de div et label

**Comment by jwallet** [comment]
fixed
